name: Terraform Module Base CI/CD Pipeline

on:
  workflow_call:
    inputs:
      concurrency_group:
        description: "Name of concurrency group to manage concurrent github action runs"
        default: ${{ github.repository }}/${{ github.event.pull_request.head.ref || github.ref }}
        required: false
        type: string
      runner_type:
        description: "Type of runner (GitHub-hosted or self-hosted)"
        required: false
        default: "ubuntu-latest"
        type: string
      terraform_version:
        description: "Terraform version used for Fmt"
        default: "latest"
        required: false
        type: string
      commit_user:
        description: "Username which should be used for commits by github action"
        default: "github-actions"
        required: false
        type: string
      commit_email:
        description: "Email which should be used for commits by github action"
        default: "noreply@github.com"
        required: false
        type: string
      tflint_config_repo:
        description: "Public repo where tflint config is stored"
        default: "acai_consulting/github-workflow-configs"
        required: false
        type: string
      tflint_config_repo_ref:
        description: "Ref or branch of tflint_config_repo"
        default: "main"
        required: false
        type: string
      tflint_config_path:
        description: 'Path to tflint config in tflint_config_repo (e.g. "aws/.tflint.hcl")'
        default: ".tflint.hcl"
        required: false
        type: string
      tflint_version:
        description: "Tflint version to use"
        default: "latest"
        required: false
        type: string
      trivy_version:
        description: "Trivy version to use"
        default: "latest"
        required: false
        type: string
      checkov_failures_allow:
        description: "Whether to abort the workflow if Checkov checks fail"
        required: false
        default: false
        type: boolean        
    outputs:
      all_steps_passed: 
        description: "all_steps_passed"
        value: ${{ jobs.terraform_fmt.outputs.diff_exists == 'false' && 
          jobs.terraform_docs.outputs.diff_exists == 'false' && 
          jobs.terraform_lint.outputs.lint_status == 'success' && 
          jobs.terraform_trivy.outputs.trivy_status == 'success'  && 
          (jobs.terraform_checkov.outputs.checkov_status == 'success' || 
          inputs.checkov_failures_allow == 'true') }}

# Ensures that only one workflow runs at a time
concurrency: ${{ inputs.concurrency_group }}

jobs:
  terraform_fmt:
    runs-on: ${{ inputs.runner_type }}
    outputs:
      fmt_status: ${{ steps.fmt.outcome }}
      diff_exists: ${{ steps.fmt_commit.outputs.diff }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Output Terraform Version
        run: terraform version

      - name: Terraform Format
        id: fmt
        run: terraform fmt -recursive

      - name: Commit Changes
        id: fmt_commit
        run: |
          git config --local user.name "${{ inputs.commit_user }}"
          git config --local user.email "${{ inputs.commit_email }}"
          if [[ -z $(git status -s) ]]; then
              echo "diff=false" >> $GITHUB_OUTPUT
          else
              echo "diff=true" >> $GITHUB_OUTPUT
          fi
          git diff-index --quiet HEAD || git commit -m "style(terraform fmt): format code" -a

      - name: Push Changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.pull_request.head.ref }}

  terraform_docs:
    needs:
      - terraform_fmt
    if: ${{ needs.terraform_fmt.outputs.diff_exists == 'false' }}
    runs-on: ${{ inputs.runner_type }}
    outputs:
      docs_status: ${{ steps.docs.outcome }}
      diff_exists: ${{ steps.docs.outputs.num_changed > 0 }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check For Submodules
        id: check_submodules
        run: |
          if [[ -d "./modules" ]]; then
              echo "dir_exists=true" >> $GITHUB_OUTPUT
          else
              echo "dir_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Run Terraform Docs
        id: docs
        uses: terraform-docs/gh-actions@v1.1.0
        with:
          working-dir: .
          recursive: ${{ steps.check_submodules.outputs.dir_exists }}
          recursive-path: modules
          output-file: README.md
          output-method: inject
          args: --sort-by required
          git-push: true
          git-push-user-name: ${{ inputs.commit_user }}
          git-push-user-email: ${{ inputs.commit_email }}
          git-commit-message: "docs(terraform-docs): update readme"

  terraform_lint:
    needs:
      - terraform_fmt
      - terraform_docs
    if: >
      needs.terraform_fmt.outputs.diff_exists == 'false' && 
      needs.terraform_docs.outputs.diff_exists == 'false'
    runs-on: ${{ inputs.runner_type }}
    outputs:
      lint_status: ${{ steps.lint.outcome }}

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: ${{ inputs.tflint_version }}

      - name: Get TFLint Config
        uses: terraform-linters/tflint-load-config-action@v2
        with:
          source-repo: ${{ inputs.tflint_config_repo }}
          source-path: "terraform/tflint/${{ inputs.tflint_config_path }}"
          source-ref: ${{ inputs.tflint_config_repo_ref }}
          destination-path: .tflint.hcl

      - name: Run TFLint
        uses: reviewdog/action-tflint@v1
        id: lint
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tflint_version: ${{ inputs.tflint_version }}
          reporter: github-pr-check
          fail_on_error: true
          filter_mode: nofilter
          level: error
          tflint_init: true

  terraform_trivy:
    needs:
      - terraform_fmt
      - terraform_docs
      - terraform_lint
    if: >
      needs.terraform_fmt.outputs.diff_exists == 'false' && 
      needs.terraform_docs.outputs.diff_exists == 'false'
    runs-on: ${{ inputs.runner_type }}
    outputs:
      trivy_status: ${{ steps.trivy.outcome }}

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Trivy
        uses: reviewdog/action-trivy@v1
        id: trivy
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          fail_on_error: true
          filter_mode: nofilter
          level: error
          flags: ""
          trivy_flags: ""
          trivy_command: config
          trivy_target: .
          trivy_version: ${{ inputs.trivy_version }}

  terraform_checkov:
    needs:
      - terraform_fmt
      - terraform_docs
      - terraform_lint
      - terraform_trivy
    if: >
      needs.terraform_fmt.outputs.diff_exists == 'false' && 
      needs.terraform_docs.outputs.diff_exists == 'false'
    runs-on: ${{ inputs.runner_type }}
    outputs:
      checkov_status : ${{ steps.checkov_summary.outputs.checkov_status }}

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Checkov and Run with Console and XML Output
        uses: bridgecrewio/checkov-action@v12
        with:
          framework: terraform
          quiet: true
          soft_fail: ${{ inputs.checkov_failures_allow }}
          download_external_modules: true
          output_format: cli, junitxml
          output_file_path: console,checkov-report.xml # folder and name of results file

      - name: Publish Checkov Test Results
        uses: dorny/test-reporter@v1.9.0
        with:
          name: Checkov Test Results
          path: ./checkov-report.xml
          reporter: java-junit
          list-suites: all
          list-tests: failed
          max-annotations: 10
          only-summary: false

      - name: Summarize Checkov Report
        id: checkov_summary
        run: |
          sudo apt-get update && sudo apt-get install -y libxml2-utils
          CHECKOV_FAILED=$(xmllint --xpath 'string(//testsuites/@failures)' checkov-report.xml)
          echo "Failed checks: $CHECKOV_FAILED"
          if [[ "$CHECKOV_FAILED" == "0" ]]; then
            echo "checkov_status=success" >> $GITHUB_OUTPUT
          else
            echo "checkov_status=failed" >> $GITHUB_OUTPUT
            exit 1
          fi     

  consume_outputs:
    needs: [terraform_fmt, terraform_docs, terraform_lint, terraform_trivy, terraform_checkov]
    runs-on: ubuntu-latest
    steps:
      - name: Use Outputs Steps
        run: |
          echo '### Workflow Outputs Summary' >> $GITHUB_STEP_SUMMARY
          echo '| Step | Status | Diff Exists |' >> $GITHUB_STEP_SUMMARY
          echo '|---|---|---|' >> $GITHUB_STEP_SUMMARY
          echo "| Terraform Format | ${{ needs.terraform_fmt.outputs.fmt_status }} | ${{ needs.terraform_fmt.outputs.fmt_diff_exists }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Terraform Docs | ${{ needs.terraform_docs.outputs.docs_status }} | ${{ needs.terraform_docs.outputs.docs_diff_exists }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Terraform Lint | ${{ needs.terraform_lint.outputs.lint_status }} | - |" >> $GITHUB_STEP_SUMMARY
          echo "| Trivy Security Scan | ${{ needs.terraform_trivy.outputs.trivy_status }} | - |" >> $GITHUB_STEP_SUMMARY
          echo "| Checkov Scan | ${{ needs.terraform_checkov.outputs.checkov_status }} | - |" >> $GITHUB_STEP_SUMMARY
